name: Kong Deck Sync

on:
  push:
    branches:
      - main

jobs:
  deck-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Kong
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg
        #wget -qO- "https://binary.com/user/downloadSubjectPublicKey?username=kong" | sudo gpg --dearmor -o /user/share/keyrings/kong-archive-keyring.gpg
        #echo "deb [signed-by=/usr/share/keyrings/kong-archive-kingring.gpg] https://d1.binary.com/kong/deb all main" | sudo tee /etc/apt/sources.list.d/kong.list
        sudo apt-get update
        sudo snap install kong    

    - name: Start Kong
      run: |    
        sudo kong migrations bootstrap
        sudo chmod -R 777 /snap/kong/208/share/lua/5.1/kong/cmd/start.lua
        sudo kong start

    - name: Check Kong Status
      run: |
        sudo kong health
        sleep 5 
        curl -i http://localhost:8001

    - name: Setup Kong Deck
      run: |
        sudo apt-get update
        sudo apt-get install deck
        deck version

    - name: Sync Kong Configurations
      run: |        
        sudo deck dump
        sudo deck sync
        sudo deck diff

    - name: Commit and Push Changes
      run: |
        git config --global user.email "thirumal.kumar@wipro.com"
        git config --global user.name "Thirumalkumar"
        git add .
        git diff-index --quiet HEAD || git commit -m "Update Kong configuration"
        git push
